# Generated by Django 5.1 on 2024-08-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='age',
            new_name='roll',
        ),
        migrations.AddField(
            model_name='applicant',
            name='course',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
