# Generated by Django 5.1 on 2024-08-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_rename_age_applicant_roll_applicant_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='roll',
        ),
    ]
