# Generated by Django 5.1 on 2024-08-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_applicant_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='roll',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
