# Generated by Django 5.1 on 2024-08-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_alter_applicant_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='course',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
