# Generated by Django 5.1 on 2024-08-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_alter_applicant_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='course',
        ),
    ]
